# model building using important features , the important features used to predict impact of the incident are : 
number, caller_id, open_by, updatedby, createdby, assigned_to, loc, category, opened_at_day, sysmodcount,


import the basic libraries 

In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
import seaborn as sns 


# import the dataset 


In [2]:
df = pd.read_csv("final data.csv")

In [3]:
df.head()

number  incidentstate  active  reassignmentcount  reopencount  sysmodcount  \
0       0              7       1                  0            0            0   
1       0              1       1                  1            0            1   
2       0              1       1                  1            0            2   
3       0              1       1                  1            0            3   
4       0              1       1                  1            0            4   

   contact_type  knowledge  upriorityconfirmation  caller_id  ...  \
0             3          1                      0       2403  ...   
1             3          1                      0       2403  ...   
2             3          1                      0       2403  ...   
3             3          1                      0       2403  ...   
4             3          1                      0       2403  ...   

   opened_at_day  opened_at_month  opened_at_year  opened_at_hr  \
0             29                2            2016             4   
1             29                2            2016             4   
2             29                2            2016             4   
3             29                2            2016             4   
4             29                2            2016             4   

   opened_at_minute  created_at_day  created_at_month  created_at_year  \
0                40              29                 2             2016   
1                40              29                 2             2016   
2                40              29                 2             2016   
3                40              29                 2             2016   
4                40              29                 2             2016   

   created_at_hr  created_at_minute  
0              4                 57  
1              4                 57  
2              4                 57  
3              4                 57  
4              4                 57  

[5 rows x 33 columns]

In [4]:
df.columns

Index(['number', 'incidentstate', 'active', 'reassignmentcount', 'reopencount',
       'sysmodcount', 'contact_type', 'knowledge', 'upriorityconfirmation',
       'caller_id', 'open_by', 'createdby', 'updatedby', 'loc', 'category',
       'symptom', 'i_impact', 'assigned_to', 'updated_day', 'updated_month',
       'updated_year', 'updated_hr', 'updated_minute', 'opened_at_day',
       'opened_at_month', 'opened_at_year', 'opened_at_hr', 'opened_at_minute',
       'created_at_day', 'created_at_month', 'created_at_year',
       'created_at_hr', 'created_at_minute'],
      dtype='object')

In [5]:
df.columns=['number','incidentstate','active','reassignmentcount','reopencount',
       'sysmodcount','contacttype','knowledge','upriorityconfirmation',
       'callerid','open_by','createdby','updatedby','loc','category',
       'symptom','iimpact','assignedto','updatedday','updatedmonth',
       'updatedyear','updatedhr','updatedminute','openedatday',
       'openedatmonth','openedatyear','openedathr','openedatminute',
       'createdatday','createdatmonth','createdatyear',
       'createdathr','createdatminute']

In [6]:
df_new=df.drop (['incidentstate','active','reassignmentcount','contacttype','knowledge','upriorityconfirmation','symptom','updatedday','updatedmonth','updatedyear','updatedhr','updatedminute','openedatmonth','openedatyear','openedathr','openedatminute','createdatday','createdatmonth','createdatyear','createdathr','createdatminute'], axis=1)

In [7]:
df_new.head(5)

number  reopencount  sysmodcount  callerid  open_by  createdby  updatedby  \
0       0            0            0      2403      397        171        746   
1       0            0            1      2403      397        171         21   
2       0            0            2      2403      397        171         21   
3       0            0            3      2403      397        171        804   
4       0            0            4      2403      397        171        703   

   loc  category  iimpact  assignedto  openedatday  
0  165       215        2          89           29  
1  165       215        2          31           29  
2  165       215        2          31           29  
3  165       215        2          31           29  
4  165       215        2          31           29

In [8]:
df_new.drop(['reopencount'],axis=1)

number  sysmodcount  callerid  open_by  createdby  updatedby  loc  \
0            0            0      2403      397        171        746  165   
1            0            1      2403      397        171         21  165   
2            0            2      2403      397        171         21  165   
3            0            3      2403      397        171        804  165   
4            0            4      2403      397        171        703  165   
...        ...          ...       ...      ...        ...        ...  ...   
141703   24915            4       116       12         10         27  204   
141704   24916            0       116       12         10        908  204   
141705   24916            1       116       12         10         60  204   
141706   24916            2       116       12         10         27  204   
141707   24916            3       116       12         10         27  204   

        category  iimpact  assignedto  openedatday  
0            215        2          89           29  
1            215        2          31           29  
2            215        2          31           29  
3            215        2          31           29  
4            215        2          31           29  
...          ...      ...         ...          ...  
141703       223        2          10           16  
141704       223        2          10           16  
141705       223        2          10           16  
141706       223        2          10           16  
141707       223        2          10           16  

[141708 rows x 11 columns]

In [9]:
X=df_new.drop("iimpact", axis=1)

In [10]:
X.head()

number  reopencount  sysmodcount  callerid  open_by  createdby  updatedby  \
0       0            0            0      2403      397        171        746   
1       0            0            1      2403      397        171         21   
2       0            0            2      2403      397        171         21   
3       0            0            3      2403      397        171        804   
4       0            0            4      2403      397        171        703   

   loc  category  assignedto  openedatday  
0  165       215          89           29  
1  165       215          31           29  
2  165       215          31           29  
3  165       215          31           29  
4  165       215          31           29

In [11]:
X.shape

(141708, 11)

In [12]:
Y = df_new['iimpact']

In [13]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: iimpact, dtype: int64

In [14]:
Y.shape

(141708,)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

# Balancing the train data  

In [17]:
from imblearn.over_sampling import SMOTE

In [18]:
smote = SMOTE()

In [19]:
X_train_smote, y_train_smote = smote.fit_resample(X_train.astype('float'), y_train)

In [20]:
from collections import Counter


In [21]:
print("Before SMOTE :",Counter(y_train))
print("After SMOTE :",Counter(y_train_smote))

Before SMOTE : Counter({2: 94155, 3: 2647, 1: 2393})
After SMOTE : Counter({2: 94155, 1: 94155, 3: 94155})


# model building

# 1. random forest classifier 

In [22]:
X_train_smote_new= X_train_smote[['number', 'callerid', 'open_by', 'updatedby', 'createdby', 'assignedto', 'loc', 'category', 'openedatday', 'sysmodcount']]
X_test_new= X_test[['number', 'callerid', 'open_by', 'updatedby', 'createdby', 'assignedto', 'loc', 'category', 'openedatday', 'sysmodcount']]

In [23]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(max_depth=27)
model_rf.fit(X_train_smote_new,y_train_smote)
   

RandomForestClassifier(max_depth=27)

In [24]:
# Predicting the model
y_predict_rf = model_rf.predict(X_test_new)

In [25]:
# Finding accuracy, precision, recall and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test,y_predict_rf))
print(classification_report(y_test,y_predict_rf))


0.9814880154305742
              precision    recall  f1-score   support

           1       0.89      0.65      0.75      1098
           2       0.99      0.99      0.99     40176
           3       0.89      0.85      0.87      1239

    accuracy                           0.98     42513
   macro avg       0.92      0.83      0.87     42513
weighted avg       0.98      0.98      0.98     42513



In [26]:
confusion_matrix(y_test,y_predict_rf)


array([[  716,   378,     4],
       [   82, 39962,   132],
       [    7,   184,  1048]], dtype=int64)

In [63]:
accuracy_rf = (716+39962+1048)/(42513)*100

# 2. decision tree 

In [27]:
# Training the model
from sklearn.tree import DecisionTreeClassifier
model_dtree=DecisionTreeClassifier()
model_dtree.fit(X_train_smote_new,y_train_smote)

DecisionTreeClassifier()

In [28]:
# Predicting the model
y_predict_dtree = model_dtree.predict(X_test_new)

In [34]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_dtree))
print(classification_report(y_test,y_predict_dtree))

0.9552607437724931
              precision    recall  f1-score   support

           1       0.44      0.60      0.51      1098
           2       0.98      0.97      0.98     40176
           3       0.70      0.81      0.75      1239

    accuracy                           0.96     42513
   macro avg       0.71      0.79      0.75     42513
weighted avg       0.96      0.96      0.96     42513



In [35]:
confusion_matrix(y_test,y_predict_dtree )

array([[  654,   427,    17],
       [  806, 38955,   415],
       [   13,   224,  1002]], dtype=int64)

In [65]:
accuracy_dtree = (654+38955+1002)/(42513)*100

#  3. k nearest neighbour

In [30]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=12,metric='euclidean') # Maximum accuracy for n=10


In [31]:
model_knn.fit(X_train_smote_new,y_train_smote)

KNeighborsClassifier(metric='euclidean', n_neighbors=12)

In [32]:
# Predicting the model
y_predict_knn = model_knn.predict(X_test_new)

In [37]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_knn))
print(classification_report(y_test,y_predict_knn))

0.8463058358619716
              precision    recall  f1-score   support

           1       0.21      0.87      0.34      1098
           2       0.99      0.84      0.91     40176
           3       0.29      0.87      0.43      1239

    accuracy                           0.85     42513
   macro avg       0.50      0.86      0.56     42513
weighted avg       0.95      0.85      0.88     42513



In [36]:
confusion_matrix(y_test,y_predict_knn)

array([[  950,   111,    37],
       [ 3558, 33946,  2672],
       [   42,   114,  1083]], dtype=int64)

In [67]:
accuracy_knn = (950+33946+1083)/(42513)*100

# 4. XGBoost classifier

In [38]:
# Training the model
from xgboost import XGBClassifier
model_xgb = XGBClassifier()


In [39]:
model_xgb.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:45:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
# Predicting the model
y_predict_xgb = model_xgb.predict(X_test_new)

In [41]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_xgb))
print(classification_report(y_test,y_predict_xgb))

0.9711147178510103
              precision    recall  f1-score   support

           1       0.81      0.43      0.56      1098
           2       0.98      0.99      0.98     40176
           3       0.80      0.80      0.80      1239

    accuracy                           0.97     42513
   macro avg       0.86      0.74      0.78     42513
weighted avg       0.97      0.97      0.97     42513



In [42]:
confusion_matrix(y_test,y_predict_xgb)

array([[  471,   624,     3],
       [  107, 39817,   252],
       [    3,   239,   997]], dtype=int64)

In [69]:
accuracy_XGB= (471+39817+997)/(42513)*100

# 5 .Artificial neural network 

In [43]:
# Training the model
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier()

In [44]:
model_mlp.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [45]:
# Predicting the model
y_predict_mlp = model_mlp.predict(X_test_new)

In [46]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_mlp))
print(classification_report(y_test,y_predict_mlp))

0.7074306682661774
              precision    recall  f1-score   support

           1       0.07      0.61      0.13      1098
           2       0.98      0.71      0.82     40176
           3       0.21      0.70      0.33      1239

    accuracy                           0.71     42513
   macro avg       0.42      0.67      0.43     42513
weighted avg       0.93      0.71      0.79     42513



In [47]:
confusion_matrix(y_test,y_predict_mlp)

array([[  670,   388,    40],
       [ 8500, 28542,  3134],
       [   79,   297,   863]], dtype=int64)

In [71]:
accuracy_mlp = (670+28542+863)/(42513)*100

# 6. naive bayes 

In [48]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [50]:
sgnb = GaussianNB()
smnb = MultinomialNB()

In [51]:
spred_gnb = sgnb.fit(X_train_smote_new,y_train_smote)

In [52]:
# Predicting the model
y_predict_sgnb = spred_gnb.predict(X_test_new)

In [53]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_sgnb))
print(classification_report(y_test,y_predict_sgnb))

0.5040105379530967
              precision    recall  f1-score   support

           1       0.04      0.43      0.08      1098
           2       0.96      0.51      0.66     40176
           3       0.05      0.46      0.10      1239

    accuracy                           0.50     42513
   macro avg       0.35      0.47      0.28     42513
weighted avg       0.91      0.50      0.63     42513



In [58]:
confusion_matrix(y_test,y_predict_sgnb )

array([[  474,   356,   268],
       [10014, 20378,  9784],
       [  250,   414,   575]], dtype=int64)

In [73]:
accuracy_gnb = (474+20378+575)/(42513)*100

In [55]:
spred_mnb = smnb.fit(X_train_smote_new,y_train_smote)

In [56]:
# Predicting the model
y_predict_smnb = spred_mnb.predict(X_test_new)

In [57]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_smnb))
print(classification_report(y_test,y_predict_smnb))

0.21012396208218662
              precision    recall  f1-score   support

           1       0.03      0.47      0.06      1098
           2       0.97      0.19      0.32     40176
           3       0.04      0.57      0.07      1239

    accuracy                           0.21     42513
   macro avg       0.35      0.41      0.15     42513
weighted avg       0.91      0.21      0.31     42513



In [59]:
confusion_matrix(y_test,y_predict_smnb)

array([[  517,   141,   440],
       [15040,  7708, 17428],
       [  393,   138,   708]], dtype=int64)

In [75]:
accuracy_mnb =(517+7708+708)/(42513)*100

In [76]:
data = {"MODEL":pd.Series(["model_rf","model_dtree","model_knn","model_xgb","model_mlp","spred_gnb ","spred_mnb"]),
        "Accuracy":pd.Series([accuracy_rf,accuracy_dtree,accuracy_knn,accuracy_XGB,accuracy_mlp,accuracy_gnb,accuracy_mnb])}
table=pd.DataFrame(data)
table 

MODEL   Accuracy
0     model_rf  98.148802
1  model_dtree  95.526074
2    model_knn  84.630584
3    model_xgb  97.111472
4    model_mlp  70.743067
5   spred_gnb   50.401054
6    spred_mnb  21.012396