In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
import seaborn as sns 

In [2]:
df = pd.read_csv("final_data.csv")

In [3]:
df

Unnamed: 0  incidentstate  active  reassignmentcount  reopencount  \
0                4              7       1                  0            0   
1                5              1       1                  1            0   
2                6              1       1                  1            0   
3                7              1       1                  1            0   
4                8              1       1                  1            0   
...            ...            ...     ...                ...          ...   
141703      141707              6       0                  1            0   
141704      141708              1       1                  0            0   
141705      141709              1       1                  1            0   
141706      141710              8       1                  1            0   
141707      141711              6       0                  1            0   

        sysmodcount  contacttype  assignmentgroup  knowledge  \
0                 0            3               70          1   
1                 1            3               24          1   
2                 2            3               24          1   
3                 3            3               24          1   
4                 4            3               24          1   
...             ...          ...              ...        ...   
141703            4            1               31          0   
141704            0            1               70          0   
141705            1            1               31          0   
141706            2            1               31          0   
141707            3            1               31          0   

        upriorityconfirmation  ...  opened_at_day  opened_at_month  \
0                           0  ...             29                2   
1                           0  ...             29                2   
2                           0  ...             29                2   
3                           0  ...             29                2   
4                           0  ...             29                2   
...                       ...  ...            ...              ...   
141703                      1  ...             16                2   
141704                      0  ...             16                2   
141705                      0  ...             16                2   
141706                      1  ...             16                2   
141707                      1  ...             16                2   

        opened_at_year  opened_at_hr  opened_at_minute  created_at_day  \
0                 2016             4                40              29   
1                 2016             4                40              29   
2                 2016             4                40              29   
3                 2016             4                40              29   
4                 2016             4                40              29   
...                ...           ...               ...             ...   
141703            2017             9                 9              27   
141704            2017            14                17              27   
141705            2017            14                17              27   
141706            2017            14                17              27   
141707            2017            14                17              27   

        created_at_month  created_at_year  created_at_hr  created_at_minute  
0                      2             2016              4                 57  
1                      2             2016              4                 57  
2                      2             2016              4                 57  
3                      2             2016              4                 57  
4                      2             2016              4                 57  
...                  ...              ...            ...                ...  
141703                 1             2

In [4]:
df.isnull().sum()

Unnamed: 0               0
incidentstate            0
active                   0
reassignmentcount        0
reopencount              0
sysmodcount              0
contacttype              0
assignmentgroup          0
knowledge                0
upriorityconfirmation    0
resolvedby               0
caller_id                0
open_by                  0
createdby                0
updatedby                0
loc                      0
category                 0
symptom                  0
i_impact                 0
assigned_to              0
updated_day              0
updated_month            0
updated_year             0
updated_hr               0
updated_minute           0
opened_at_day            0
opened_at_month          0
opened_at_year           0
opened_at_hr             0
opened_at_minute         0
created_at_day           0
created_at_month         0
created_at_year          0
created_at_hr            0
created_at_minute        0
dtype: int64

In [5]:
X=df.drop("i_impact",axis=1)


In [6]:
X.head()

Unnamed: 0  incidentstate  active  reassignmentcount  reopencount  \
0           4              7       1                  0            0   
1           5              1       1                  1            0   
2           6              1       1                  1            0   
3           7              1       1                  1            0   
4           8              1       1                  1            0   

   sysmodcount  contacttype  assignmentgroup  knowledge  \
0            0            3               70          1   
1            1            3               24          1   
2            2            3               24          1   
3            3            3               24          1   
4            4            3               24          1   

   upriorityconfirmation  ...  opened_at_day  opened_at_month  opened_at_year  \
0                      0  ...             29                2            2016   
1                      0  ...             29                2            2016   
2                      0  ...             29                2            2016   
3                      0  ...             29                2            2016   
4                      0  ...             29                2            2016   

   opened_at_hr  opened_at_minute  created_at_day  created_at_month  \
0             4                40              29                 2   
1             4                40              29                 2   
2             4                40              29                 2   
3             4                40              29                 2   
4             4                40              29                 2   

   created_at_year  created_at_hr  created_at_minute  
0             2016              4                 57  
1             2016              4                 57  
2             2016              4                 57  
3             2016              4                 57  
4             2016              4                 57  

[5 rows x 34 columns]

In [7]:
Y = df['i_impact']

In [8]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: i_impact, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

In [11]:
from imblearn.over_sampling import SMOTE

In [12]:
smote = SMOTE()

In [13]:
X_train_smote, y_train_smote = smote.fit_resample(X_train.astype('float'), y_train)

In [14]:
from collections import Counter
print("Before SMOTE :",Counter(y_train))
print("After SMOTE :",Counter(y_train_smote))

Before SMOTE : Counter({2: 94155, 3: 2647, 1: 2393})
After SMOTE : Counter({2: 94155, 1: 94155, 3: 94155})


In [15]:
X_train_smote_new= X_train_smote[['caller_id','open_by','loc','category']]
X_test_new= X_test[['caller_id','open_by','loc','category']]

In [16]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(max_depth=27)
model_rf.fit(X_train_smote_new,y_train_smote)


RandomForestClassifier(max_depth=27)

In [17]:
# Predicting the model
y_predict_rf = model_rf.predict(X_test_new)

In [18]:
# Finding accuracy, precision, recall and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test,y_predict_rf))
print(classification_report(y_test,y_predict_rf))


0.9785947827723285
              precision    recall  f1-score   support

           1       0.68      0.93      0.79      1098
           2       1.00      0.98      0.99     40176
           3       0.78      0.95      0.86      1239

    accuracy                           0.98     42513
   macro avg       0.82      0.95      0.88     42513
weighted avg       0.98      0.98      0.98     42513



In [19]:
confusion_matrix(y_test,y_predict_rf)


array([[ 1017,    64,    17],
       [  452, 39403,   321],
       [   21,    35,  1183]], dtype=int64)

In [75]:
accuracy_rf = (1017+39403+1183)/(42513)*100

In [21]:
# Training the model
from sklearn.tree import DecisionTreeClassifier
model_dtree=DecisionTreeClassifier()
model_dtree.fit(X_train_smote_new,y_train_smote)

DecisionTreeClassifier()

In [22]:
# Predicting the model
y_predict_dtree = model_dtree.predict(X_test_new)

In [23]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_dtree))
print(classification_report(y_test,y_predict_dtree))

0.9775598052360455
              precision    recall  f1-score   support

           1       0.66      0.93      0.78      1098
           2       1.00      0.98      0.99     40176
           3       0.78      0.95      0.86      1239

    accuracy                           0.98     42513
   macro avg       0.81      0.96      0.87     42513
weighted avg       0.98      0.98      0.98     42513



In [24]:
confusion_matrix(y_test,y_predict_dtree )

array([[ 1023,    59,    16],
       [  496, 39354,   326],
       [   22,    35,  1182]], dtype=int64)

In [76]:
accuracy_dtree = (1023+39354+1182)/(42513)*100

In [26]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=12,metric='euclidean') # Maximum accuracy for n=10


In [27]:
model_knn.fit(X_train_smote_new,y_train_smote)

KNeighborsClassifier(metric='euclidean', n_neighbors=12)

In [28]:
# Predicting the model
y_predict_knn = model_knn.predict(X_test_new)

In [29]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_knn))
print(classification_report(y_test,y_predict_knn))

0.8995601345470797
              precision    recall  f1-score   support

           1       0.30      0.95      0.45      1098
           2       1.00      0.90      0.94     40176
           3       0.40      0.93      0.56      1239

    accuracy                           0.90     42513
   macro avg       0.57      0.92      0.65     42513
weighted avg       0.96      0.90      0.92     42513



In [30]:
confusion_matrix(y_test,y_predict_knn)

array([[ 1038,    39,    21],
       [ 2425, 36051,  1700],
       [   28,    57,  1154]], dtype=int64)

In [77]:
accuracy_knn = (1038+36051+1154)/(42513)*100

In [32]:
# Training the model
from xgboost import XGBClassifier
model_xgb = XGBClassifier()


In [33]:
model_xgb.fit(X_train_smote_new,y_train_smote)

C:\Users\SAI HARI\anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:06:44] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [34]:
# Predicting the model
y_predict_xgb = model_xgb.predict(X_test_new)

In [35]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_xgb))
print(classification_report(y_test,y_predict_xgb))

0.9116035095147367
              precision    recall  f1-score   support

           1       0.36      0.86      0.51      1098
           2       1.00      0.91      0.95     40176
           3       0.38      0.93      0.54      1239

    accuracy                           0.91     42513
   macro avg       0.58      0.90      0.67     42513
weighted avg       0.96      0.91      0.93     42513



In [36]:
confusion_matrix(y_test,y_predict_xgb)

array([[  944,   126,    28],
       [ 1634, 36660,  1882],
       [   38,    50,  1151]], dtype=int64)

In [78]:
accuracy_XGB= (944+36660+1151)/(42513)*100

In [38]:
# Training the model
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier()

In [39]:
model_mlp.fit(X_train_smote_new,y_train_smote)

MLPClassifier()

In [40]:
# Predicting the model
y_predict_mlp = model_mlp.predict(X_test_new)

In [41]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_mlp))
print(classification_report(y_test,y_predict_mlp))

0.4995648389904265
              precision    recall  f1-score   support

           1       0.05      0.51      0.08      1098
           2       0.98      0.49      0.65     40176
           3       0.10      0.88      0.19      1239

    accuracy                           0.50     42513
   macro avg       0.38      0.63      0.31     42513
weighted avg       0.93      0.50      0.62     42513



In [42]:
confusion_matrix(y_test,y_predict_mlp)

array([[  561,   286,   251],
       [11489, 19588,  9099],
       [   84,    66,  1089]], dtype=int64)

In [79]:
accuracy_mlp = (561+19588+1089)/(42513)*100

In [44]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [45]:
sgnb = GaussianNB()
smnb = MultinomialNB()

In [46]:
spred_gnb = sgnb.fit(X_train_smote_new,y_train_smote)

In [47]:
# Predicting the model
y_predict_sgnb = spred_gnb.predict(X_test_new)

In [48]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_sgnb))
print(classification_report(y_test,y_predict_sgnb))

0.5137487356808506
              precision    recall  f1-score   support

           1       0.03      0.27      0.06      1098
           2       0.97      0.52      0.67     40176
           3       0.06      0.63      0.12      1239

    accuracy                           0.51     42513
   macro avg       0.36      0.47      0.28     42513
weighted avg       0.92      0.51      0.64     42513



In [49]:
confusion_matrix(y_test,y_predict_sgnb )

array([[  299,   449,   350],
       [ 8326, 20765, 11085],
       [  309,   153,   777]], dtype=int64)

In [80]:
accuracy_gnb = (299+20765+777)/(42513)*100

In [51]:
spred_mnb = smnb.fit(X_train_smote_new,y_train_smote)

In [52]:
# Predicting the model
y_predict_smnb = spred_mnb.predict(X_test_new)

In [53]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_smnb))
print(classification_report(y_test,y_predict_smnb))

0.5189471455789993
              precision    recall  f1-score   support

           1       0.04      0.13      0.06      1098
           2       0.96      0.53      0.68     40176
           3       0.04      0.59      0.08      1239

    accuracy                           0.52     42513
   macro avg       0.35      0.42      0.27     42513
weighted avg       0.91      0.52      0.65     42513



In [54]:
confusion_matrix(y_test,y_predict_smnb)

array([[  145,   476,   477],
       [ 3289, 21183, 15704],
       [  112,   393,   734]], dtype=int64)

In [81]:
accuracy_mnb =(145+21183+734)/(42513)*100

In [82]:
data = {"MODEL":pd.Series(["model_rf","model_dtree","model_knn","model_xgb","model_mlp","spred_gnb ","spred_mnb"]),
        "Accuracy":pd.Series([accuracy_rf,accuracy_dtree,accuracy_knn,accuracy_XGB,accuracy_mlp,accuracy_gnb,accuracy_mnb])}
table=pd.DataFrame(data)
table 

MODEL   Accuracy
0     model_rf  97.859478
1  model_dtree  97.755981
2    model_knn  89.956013
3    model_xgb  91.160351
4    model_mlp  49.956484
5   spred_gnb   51.374874
6    spred_mnb  51.894715

In [62]:
#Splitting Training and Test Set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)


In [63]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [67]:
#Fitting Kernel_SVM Classification Model
from sklearn.svm import SVC
model1 = DecisionTreeClassifier() 
model1.fit(X_train,Y_train)

DecisionTreeClassifier()

In [91]:
#Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=model1, X = X_train_smote, y = y_train_smote , cv=10)
accuracy.mean()
accuracy.std()
#Predicting the test set results
y_pred = model1.predict(X_test)

In [92]:
accuracy

array([0.92643467, 0.98428152, 0.98314865, 0.98300704, 0.98470634,
       0.98290023, 0.98389152, 0.98406854, 0.98413935, 0.98173193])